name: static-checks


jobs:
  versionExtract:
    name: Get min/max versions
    runs-on: ubuntu-latest

  format:
    name: Check code format
    runs-on: ubuntu-latest
    needs: versionExtract

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terraform v${{ needs.versionExtract.outputs.maxVersion }}
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ needs.versionExtract.outputs.maxVersion }}

      - name: Check Terraform format changes
        run: terraform fmt --recursive